# Extra autostart processes
# exec-once = uwsm-app -- my-service
#exec-once = $HOME/.config/hypr/scripts/waybar_auto_hide &
#exec-once = vicinae server
exec-once = hyprpm reload
exec-once = sleep 2 && qpwgraph
exec-once = sleep 10 && hyprctl reload
exec-once = sleep 35 && hyprctl reload