background            #121212
foreground            #ffffff

# black
color0  #121212
color8  #9e9e9e

# red
color1  #8d6cc8
color9  #b58aff

# green
color2  #7579d3
color10 #9999ff

# yellow
color3  #6576d2
color11 #8896ff

# blue
color4  #7579d2
color12 #9999ff

# magenta
color5  #8b6cc8
color13 #b38aff

#cyan
color6  #7579d3
color14 #9999ff

#white
color7  #ffffff
color15 #ffffff


